// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MsgDefineClient.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace ProtoMsg
{

    [global::ProtoBuf.ProtoContract(Name = @"MSG_SERVER_REGIST")]
    public partial class MsgServerRegist : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public MsgRegServerInfo Info { get; set; }
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_SERVER_REGIST_REPLY")]
    public partial class MsgServerRegistReply : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public MsgRegServerInfo Info { get; set; }
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_MESSAGE_ERROR")]
    public partial class MsgMessageError : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1)]
        public int nErrorKey { get; set; }
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLIENT_KEEP_LIVE")]
    public partial class MsgClientKeepLive : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_CLIENT_KEEP_LIVE_ACK")]
    public partial class MsgClientKeepLiveAck : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2LG_REGIST")]
    public partial class MsgCl2lgRegist : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public MsgRegServerInfo Info { get; set; }
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2LG_REGIST_REPLY")]
    public partial class MsgCl2lgRegistReply : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public MsgRegServerInfo Info { get; set; }
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2LG_LOGIN")]
    public partial class MsgCl2lgLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string strWebSession { get; set; } = "";
        
        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string strAccount { get; set; } = "";
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2LG_LOGIN_REPLY")]
    public partial class MsgCl2lgLoginReply : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1)]
        public ulong u64UUID { get; set; }
        
        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string strLoginSession { get; set; } = "";
        
        [global::ProtoBuf.ProtoMember(3)]
        public MsgNetAddress netAddr { get; set; }
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_REGIST")]
    public partial class MsgCl2gsRegist : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public MsgRegServerInfo Info { get; set; }
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_REGIST_REPLY")]
    public partial class MsgCl2gsRegistReply : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1, Name = @"info")]
        public MsgRegServerInfo Info { get; set; }
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_LOGIN")]
    public partial class MsgCl2gsLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1)]
        public ulong u64UUID { get; set; }
        
        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string strLoginSession { get; set; } = "";
        
        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string strAccount { get; set; } = "";
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_CL2GS_LOGIN_REPLY")]
    public partial class MsgCl2gsLoginReply : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string strOfflineSession { get; set; } = "";
        
        [global::ProtoBuf.ProtoMember(2)]
        public int n32Flag { get; set; }
        
        [global::ProtoBuf.ProtoMember(3)]
        public MsgPlayerBase playerBase { get; set; }
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_LOGIN_DATA_READY")]
    public partial class MsgGs2clLoginDataReady : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
    }
    
    [global::ProtoBuf.ProtoContract(Name = @"MSG_GS2CL_KICK")]
    public partial class MsgGs2clKick : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        
        [global::ProtoBuf.ProtoMember(1)]
        public uint u32DelayTime { get; set; }
        
        [global::ProtoBuf.ProtoMember(2)]
        public uint u32Reason { get; set; }
        
    }
    
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
