// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MsgErrorDefine.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public enum eMessageError
{
    eNotMsgError = 0,
    eUnDefinedError = 1,
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
